"""empty message

Revision ID: 1a4a90876f94
Revises: a7136d31ded4
Create Date: 2023-03-08 13:45:57.698588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4a90876f94'
down_revision = 'a7136d31ded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pup', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
